### ISSUE TITLE
KeyError: "Unable to open object (object 'param_0' doesn't exist)"

### ISSUE THREAD

**Issue by JeetShah10** [keunwoochoi/Auralisation#3]
Hello @keunwoochoi  @mpariente 
While loading weights from .keras file giving me this error. Can anyone help me with this?

Traceback (most recent call last):
  File "example.py", line 33, in <module>
    W, layer_names = auralise.load_weights()
  File "D:\MP_ASR\Auralisation-master\auralise.py", line 175, in load_weights
    print(f[key]['param_0'][:,:,:,:])
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\Users\Jeet\Anaconda3\lib\site-packages\h5py\_hl\group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'param_0' doesn't exist)"

Thanks in advance.

**Comment by keunwoochoi** [comment]
Hi, sorry but I don't know and can't remember anything that could help this. I think this could be Keras version issue but that's all I can say.
